### PR TITLE
GH Toolset update: codeowners

### PR DESCRIPTION
**Pull request by BrandonPacewic**
This change will now request a review from the organization team `ogpcleaders`. It then will request a review from @BrandonPacewic and @Galaxy25 respectively. Makes it easier to update who has access to reviewing and maintaining in the future.

### CODE REVIEW

**Comment by BrandonPacewic** [comment]
Approved ✅

**Comment by Galaxy25** [comment]
@BrandonPacewic Are we the only one considered OGPC Leader?

**Comment by BrandonPacewic** [comment]
> @BrandonPacewic Are we the only one considered OGPC Leader?

That's correct. Currently only me and you are on the team.

**Review by Galaxy25 — APPROVED** [review]

**Comment by BrandonPacewic** [comment]
I'm getting ready to merge and updating the change log - please @me if any other changes are pushed.

**Pull request merged**
