### PR TITLE
Initialize 2D Template

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Went ahead and made the base project with the Unity 2d template. Should be all ready to go now.

### CODE REVIEW

**Comment by BrandonPacewic** [comment]
Looks like the clang format check is not working, will worry about that later.

**Comment by BrandonPacewic** [comment]
#### Done making changes

**Review by Galaxy25 — APPROVED** [review]
The gitignore file seems to be working.

**Comment by BrandonPacewic** [comment]
> The gitignore file seems to be working.

Yup hopefully we don't go through that period again where we were updating millions of lines of code 😹

**Pull request merged**
