### PR TITLE
GH Pages initial setup

### PR DESCRIPTION
**Pull request by BrandonPacewic**
Start of the website. Basic setup includes:

- Removal of all Unity files
- Start of `index.html` (main page)
- Dark mode coloring
- `.gitignore` for `.js` files
  - Looking to do the scripting in typescript (`.ts`)

I want to add some sort of status chart tracking commits, prs and issues. Something like the [STL Status Chart](https://microsoft.github.io/STL/).

## 📈 Visit [brandonpacewic.github.io/FlappyBird/](https://brandonpacewic.github.io/FlappyBird/) for a live preview.

### CODE REVIEW

**Review by JakeSmig — APPROVED** [review]
Great service 10/10 food

**Review by Galaxy25 — APPROVED** [review]
Looks good

**Comment by BrandonPacewic** [comment]
In the future @Galaxy25 please refrain from merging PR's until I update the changelog. Thanks 😸

**Comment by BrandonPacewic** [comment]
Changelog updated 📈

**Comment by BrandonPacewic** [comment]
@Galaxy25 do you know why all of these commits are showing up separately? Usually squashing the commits removes the individual commit messages.

**Comment by Galaxy25** [comment]
@BrandonPacewic I don't use squash often. The only thing I could think of that would cause this would be merging it before squashing or during pull requests all commits are shown despite squashing

**Pull request merged**
